name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - name: 'Create .env file'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: 'Launch Servers' 
      run: |
        sudo pm2 stop all
        sudo pm2 start index.js
        cd verify
        pm2 delete uvicorn
        pm2 start "uvicorn app:app --host 127.0.0.1 --port 8001" --name uvicorn


# Functions # 
# --------- #
# sudo pm2 start index.js
# pm2 delete uvicorn
# pm2 start "uvicorn app:app --host 127.0.0.1 --port 8001" --name uvicorn